### ISSUE TITLE
Warning: this code is still in progress and not yet in as alpha release stage.

### ISSUE THREAD

**Issue by jerome-diver** [andrewjstryker/tmux-airline#4]
Is this project no more maintain ? Where to find the maintained one ?

**Comment by andrewjstryker** [comment]
I'm afraid that this is a very part time project for me. I use it every day. But that's different than having a well-tested project suitable for wide distribution.

**Comment by jerome-diver** [comment]
i understand, i push one star up because it is still a nice project.
have a good day.
